### ISSUE TITLE
dimensions of objects

### ISSUE THREAD

**Issue by mayman99** [cy94/sceneformer#1]
Thanks for the great paper and code,

I'm trying to use your model and I've a question regarding the implementation,
about the contents of the `model_dims.pkl`, in the paper you say `Similarly the dimensions of each object; length, width and height or (l, w, h) are scaled and quantized`
given how you read `model_dims.pkl`, it seems the scaling part at least was not implemented, right?

Best regards,
Mohamad.

**Comment by cy94** [comment]
Thanks for your interest, model scaling is done here: https://github.com/cy94/sceneformer/blob/master/transforms/scene.py#L569

**Comment by mayman99** [comment]
Thanks, I miss understood, I thought they would be scaled against room size like the location was

**Comment by k-bobin** [comment]
> Thanks, I miss understood, I thought they would be scaled against room size like the location was

Hi, if you still have access to SUNCG dataset could you share it for me? 
If you have, please email me. I'd really appreciate it.

My email is kbb8009@gmail.com

**Comment by mayman99** [comment]
I no longer have access to it ... unfortunately .. I really wish I could have access it again :D 

> > Thanks, I miss understood, I thought they would be scaled against room size like the location was
> 
> Hi, if you still have access to SUNCG dataset could you share it for me? If you have, please email me. I'd really appreciate it.
> 
> My email is [kbb8009@gmail.com](mailto:kbb8009@gmail.com)
