### ISSUE TITLE
conda env create --file environment.yaml error

### ISSUE THREAD

**Issue by Song-xx** [cy94/sceneformer#10]
conda env create --name sceneformer3  --file environment.yaml 

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/root/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/root/anaconda3/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/root/anaconda3/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 88, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/root/anaconda3/lib/python3.8/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/root/anaconda3/lib/python3.8/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/root/anaconda3/lib/python3.8/site-packages/conda_env/env.py", line 166, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/root/anaconda3/lib/python3.8/site-packages/conda_env/env.py", line 144, in from_yaml
        data = validate_keys(data, kwargs)
      File "/root/anaconda3/lib/python3.8/site-packages/conda_env/env.py", line 37, in validate_keys
        new_data = data.copy() if data else {}
    AttributeError: 'str' object has no attribute 'copy'
    
    
    who knows what is wrong with my operation,conda version or something else ?

**Comment by k-bobin** [comment]
> conda env create --name sceneformer3 --file environment.yaml
> 
> # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> ```
> Traceback (most recent call last):
>   File "/root/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
>     return func(*args, **kwargs)
>   File "/root/anaconda3/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
>     exit_code = getattr(module, func_name)(args, parser)
>   File "/root/anaconda3/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 88, in execute
>     spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
>   File "/root/anaconda3/lib/python3.8/site-packages/conda_env/specs/__init__.py", line 43, in detect
>     if spec.can_handle():
>   File "/root/anaconda3/lib/python3.8/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
>     self._environment = env.from_file(self.filename)
>   File "/root/anaconda3/lib/python3.8/site-packages/conda_env/env.py", line 166, in from_file
>     return from_yaml(yamlstr, filename=filename)
>   File "/root/anaconda3/lib/python3.8/site-packages/conda_env/env.py", line 144, in from_yaml
>     data = validate_keys(data, kwargs)
>   File "/root/anaconda3/lib/python3.8/site-packages/conda_env/env.py", line 37, in validate_keys
>     new_data = data.copy() if data else {}
> AttributeError: 'str' object has no attribute 'copy'
> 
> 
> who knows what is wrong with my operation,conda version or something else ?
> ```

Hi I'm looking for someone who has access to SUNCG dataset.
do you still have one ?
if you have, could you email me? I'd really appreciate it.

My email is kbb8009@gmail.com
