### ISSUE TITLE
error when pickl.load('35.pkl')

### ISSUE THREAD

**Issue by Song-xx** [cy94/sceneformer#11]
room_pkl = pickle.load(f)
AttributeError: Can't get attribute 'Wall' on <module 'data.house' from '/mnt/cfs/sceneformer/data/house.py'>

how to load the pkl file?

**Comment by Song-xx** [comment]
i solve it with  add a line  from data import * ,which copy planit/data/house.py into data here

**Comment by k-bobin** [comment]
> room_pkl = pickle.load(f) AttributeError: Can't get attribute 'Wall' on <module 'data.house' from '/mnt/cfs/sceneformer/data/house.py'>
> 
> how to load the pkl file?

I'm having a hard time to find a person who still has access to SUNCG dataset.
if you still have one, could you please share it for me?
I'd really appreciate it!
