### ISSUE TITLE
How to prepare dataset 

### ISSUE THREAD

**Issue by k-bobin** [cy94/sceneformer#12]
Could you elaborate how to prepare SUNCG dataset? 

I really want to test your model. 
I'm having a trouble to get ready for SUNCG dataset . 
Please help me out!!!

**Comment by cy94** [comment]
Hi, we don't support anything related to the SUNCG dataset. Can you try this script? https://github.com/cy94/sceneformer/issues/2

**Comment by k-bobin** [comment]
> Hi, we don't support anything related to the SUNCG dataset. Can you try this script? #2

I think my words are misleading. What I was curious about is not how to prepare the dataset, but how to get the SUNCG dataset itself in the first place.  I can't experiment with your code because there's no SUNCG dataset itself
Is there any other alternative dataset to test?

I'd really appreciate if you share it for me

**Comment by cy94** [comment]
Hi, I don't have access to it either. Maybe you could check in the other issues or repos if someone has access
