### ISSUE TITLE
About model_dims.pkl 

### ISSUE THREAD

**Issue by lilinyuanvr** [cy94/sceneformer#2]
thanks for your great paper
i use the scripts [creat_data.py](https://github.com/brownvc/deep-synth/blob/master/deep-synth/create_data.py) to process suncg dataset, but it did not generate the model_dims.pkl file.

is there any scripts i can use to generate model_dims.pkl on suncg dataset?

Best regards,
Li

**Comment by Xinpeng-Wang** [comment]
The model_dims.pkl is created using the script from fast-synth. 
https://github.com/brownvc/fast-synth/blob/master/scene-synth/obj_dims.py

**Comment by lilinyuanvr** [comment]
thanks !

**Comment by Mr-Faceless** [comment]
hello，could you please share the suncg datasets with me ?
Thansk so much! My email is [15005563803@163.com](mailto:15005563803@163.com).

**Comment by cy94** [comment]
Hey, unfortunately we don't have access to the dataset any more

**Comment by Mr-Faceless** [comment]
> > hello，could you please share the suncg datasets with me ? Thansk so much! My email is [15005563803@163.com](mailto:15005563803@163.com).
> 
> Have you obtained the suncg dataset? if done, could you share the dataset with me? I'd really appreciate it my email is [kbb8009@gmail.com](mailto:kbb8009@gmail.com)

sorry，I dont have the suncg dataset too.

**Comment by k-bobin** [comment]
> > > hello，could you please share the suncg datasets with me ? Thansk so much! My email is [15005563803@163.com](mailto:15005563803@163.com).
> > 
> > 
> > Have you obtained the suncg dataset? if done, could you share the dataset with me? I'd really appreciate it my email is [kbb8009@gmail.com](mailto:kbb8009@gmail.com)
> 
> sorry，I dont have the suncg dataset too.

have you found any alternative dataset to test the code? if it works, could you share the name of dataset or link  for me?

**Comment by Mr-Faceless** [comment]
> > > > hello，could you please share the suncg datasets with me ? Thansk so much! My email is [15005563803@163.com](mailto:15005563803@163.com).
> > > 
> > > 
> > > Have you obtained the suncg dataset? if done, could you share the dataset with me? I'd really appreciate it my email is [kbb8009@gmail.com](mailto:kbb8009@gmail.com)
> > 
> > 
> > sorry，I dont have the suncg dataset too.
> 
> have you found any alternative dataset to test the code? if it works, could you share the name of dataset or link for me?

I cant find any dataset which can test the code. so I gave up trying this code last year.

**Comment by k-bobin** [comment]
> > > > > hello，could you please share the suncg datasets with me ? Thansk so much! My email is [15005563803@163.com](mailto:15005563803@163.com).
> > > > 
> > > > 
> > > > Have you obtained the suncg dataset? if done, could you share the dataset with me? I'd really appreciate it my email is [kbb8009@gmail.com](mailto:kbb8009@gmail.com)
> > > 
> > > 
> > > sorry，I dont have the suncg dataset too.
> > 
> > 
> > have you found any alternative dataset to test the code? if it works, could you share the name of dataset or link for me?
> 
> I cant find any dataset which can test the code. so I gave up trying this code last year.

Sorry to hear that.
If you have tried this code before, you must been looking for other codes as well.
If there is any other code you think it is worthy to try, could you please share it for me?

So far I've tried ATISS" Autoregressive Transformers for Indoor Scene Synthesis"

**Comment by Mr-Faceless** [comment]
> > > > > > hello，could you please share the suncg datasets with me ? Thansk so much! My email is [15005563803@163.com](mailto:15005563803@163.com).
> > > > > 
> > > > > 
> > > > > Have you obtained the suncg dataset? if done, could you share the dataset with me? I'd really appreciate it my email is [kbb8009@gmail.com](mailto:kbb8009@gmail.com)
> > > > 
> > > > 
> > > > sorry，I dont have the suncg dataset too.
> > > 
> > > 
> > > have you found any alternative dataset to test the code? if it works, could you share the name of dataset or link for me?
> > 
> > 
> > I cant find any dataset which can test the code. so I gave up trying this code last year.
> 
> Sorry to hear that. If you have tried this code before, you must been looking for other codes as well. If there is any other code you think it is worthy to try, could you please share it for me?
> 
> So far I've tried ATISS" Autoregressive Transformers for Indoor Scene Synthesis"

I've tried ATISS too, I think [LEGO-Net](https://github.com/QiuhongAnnaWei/LEGO-Net) may be worthy to try but I have no time to do it.

**Comment by lphhh123** [comment]
> > > > > > > hello，could you please share the suncg datasets with me ? Thansk so much! My email is [15005563803@163.com](mailto:15005563803@163.com).
> > > > > > 
> > > > > > 
> > > > > > Have you obtained the suncg dataset? if done, could you share the dataset with me? I'd really appreciate it my email is [kbb8009@gmail.com](mailto:kbb8009@gmail.com)
> > > > > 
> > > > > 
> > > > > sorry，I dont have the suncg dataset too.
> > > > 
> > > > 
> > > > have you found any alternative dataset to test the code? if it works, could you share the name of dataset or link for me?
> > > 
> > > 
> > > I cant find any dataset which can test the code. so I gave up trying this code last year.
> > 
> > 
> > Sorry to hear that. If you have tried this code before, you must been looking for other codes as well. If there is any other code you think it is worthy to try, could you please share it for me?
> > So far I've tried ATISS" Autoregressive Transformers for Indoor Scene Synthesis"
> 
> I've tried ATISS too, I think [LEGO-Net](https://github.com/QiuhongAnnaWei/LEGO-Net) may be worthy to try but I have no time to do it.

Hello, I have been trying to replicate ATISS recently but encountered some difficulties. Have you successfully replicated ATISS? May I ask you some questions? My email is lp_daydayup@163.com.
