### ISSUE TITLE
the model_dims.pkl

### ISSUE THREAD

**Issue by JackW987** [cy94/sceneformer#6]
Hi,after I run the script.py which the deep synth have,I get the filtered room data,but the train code need "model_dims.pkl",I just have "model_prior.pkl" ,"model_frequency.pkl","fine_categories_frequency","final_categories_frequency" and "coarse_categories_frequency",which pkl files is the "model_dims.pkl"?

**Comment by lbf4616** [comment]
[here](https://github.com/cy94/sceneformer/issues/2)

**Comment by JackW987** [comment]
> [here](https://github.com/cy94/sceneformer/issues/2) by the way can you share the suncg datasets with me?

Thanks so much ! please give me your email,I will contact you later.

**Comment by lbf4616** [comment]
> > [here](https://github.com/cy94/sceneformer/issues/2) by the way can you share the suncg datasets with me?
> 
> Thanks so much ! please give me your email,I will contact you later.

Thanks, lbf4616@163.com

**Comment by Mr-Faceless** [comment]
hello，could you please share the suncg datasets with me ?
Thansk so much! My email is 15005563803@163.com.
